stages: 
  - deploy
  - release-automation
  - deploy-validation
  - release-validation

variables:
  PROJECT: awa64997-easytravelv2
  STAGE: quality-gate
  PRODUCT: www
  VERSION: 1.1.3
  BUILDID: $CI_JOB_ID
  DTTOKEN: $DTTOKEN
  DTSYNTHETICTOKEN: $DTSYNTHETICTOKEN
  DTURL: $DTURL
  CATOKEN: $CATOKEN
  CAURL: "https://awa64997.cloudautomation.sprint.dynatracelabs.com"
  IDENTIFIER: "[Kubernetes]app:easytravel-www"
  REMURL: https://url.com1
  OWNER: arijan.zenuni@dynatrace.com
  SHARED: "true"
  PRESET: "true"
  TIMEFRAME: now-30m
  MINUTEDIFF: 5
  DAYDIFF: 0
  DAYSTART: 0
  PASS: "100"
  SLO: ""
  #SLO: "-slo"
  DASHBOARD: "-dashboard"
  LOGGER: "INFO" #INFO,DEBUG,ERROR

deploy:
  stage: deploy
  script: 
    - echo "Deploying $VERSION"

release-automation:
  image: "python"
  stage: release-automation
  script:
    - cd release_automation/
    - pip install --upgrade pip
    - pip install -r stable-req.text
    #- python releaseauto.py -dtUrl $DTURL -dtToken $DTTOKEN -identifier $IDENTIFIER -ver $VERSION -proj $PROJECT -product $PRODUCT -stage $STAGE -remUrl $REMURL -owner $OWNER -shared $SHARED -preset $PRESET -timeFrame $TIMEFRAME -pass $PASS -slo -dashboard
    - python releaseauto.py -dtUrl $DTURL -dtToken $DTTOKEN -identifier $IDENTIFIER -ver $VERSION -proj $PROJECT -product $PRODUCT -stage $STAGE -remUrl $REMURL -owner $OWNER -shared $SHARED -preset $PRESET -timeFrame $TIMEFRAME -pass $PASS $SLO $DASHBOARD -l $LOGGER
deploy-validation:
  image: "python"
  stage: deploy-validation
  script:
    - cd deploy_validation/
    - pip install --upgrade pip
    - pip install -r stable-req.text
    - python validation.py -token $DTSYNTHETICTOKEN -uri $DTURL -proj $PROJECT -product $PRODUCT -stage $STAGE -l $LOGGER
    
release-validation:
  image: "python"
  stage: release-validation
  script:
    - cd release_validation/
    - pip install --upgrade pip
    - pip install -r stable-req.text
    - python evaluation.py -service $PRODUCT -stage $STAGE -project $PROJECT -buildNumber $BUILDID -token $CATOKEN -uri $CAURL -daydiff $DAYDIFF -daystart $DAYSTART -mindiff $MINUTEDIFF -l $LOGGER