configs:
  - id: globalWebAnomalyDetect
    type:
      settings:
        schema: builtin:anomaly-detection.rum-web
        scope: environment
    config:
      name: globalWebAnomalyDetect
      template: object.json
      skip: false
      parameters:
        default: true
        resp:
          ###################
          ## resp - responseTime
          ## Fields:
          ## enabled - enabled
          ## mode - detectionMode - "auto","fixed"
          ## degMilli (both) - degradationMilliseconds 
          ## degPercent (auto) - degradationPercent
          ## degSlowestMilli (both) - slowestDegradationMilliseconds
          ## degSlowestPercent (auto) - slowestDegradationPercent
          ## actPerMin (both) - actionsPerMinute
          ## abState (both) - minutesAbnormalState
          ## sens (fixed) - sensitivity - "low","medium","high"
          ##############
          type: value
          value:
            enabled: true
            mode: "auto"
            degMilli: 399
            degPercent: 10
            degSlowestMilli: 1000
            degSlowestPercent: 100
            actPerMin: 15
            abState: 1
            sens: "low"
        error:
          ###################
          ## error - errorRate
          ## Fields:
          ## enabled - enabled
          ## mode - detectionMode - "auto","fixed"
          ## absInc (auto) - absoluteIncrease 
          ## relInc (auto) - relativeIncrease
          ## actPerMin (both)  - actionsPerMinute
          ## abState (both) - minutesAbnormalState
          ## maxFailInc (fixed) - maxFailureRateIncrease
          ## errorReqPerMin (fixed) - errorRateReqPerMin
          ## sens (fixed) - sensitivity - "low","medium","high"
          ##############
          type: value
          value:
            enabled: true
            mode: "auto"
            absInc: 50
            relInc: 100
            actPerMin: 15
            abState: 1
            maxFailInc: 0
            errorReqPerMin: 10
            sens: "low"
        drop:
          ###################
          ## drop - trafficDrops
          ## Fields:
          ## enabled - enabled
          ## percent - trafficDropPercentage
          ## abState - abnormalStateAbnormalState
          ##############
          type: value
          value:
            enabled: false
            percent: 150
            abState: 2
        spike:
          ###################
          ## spike - trafficSpikes
          ## Fields:
          ## enabled - enabled
          ## percent - trafficSpikePercentage
          ## abState - minutesAbnormalState
          ##############
          type: value
          value:
            enabled: false
            percent: 150
            abState: 2