configs:
  - id: globalMobileAnomalyDetect
    type:
      settings:
        schema: builtin:anomaly-detection.rum-mobile
        scope: environment
    config:
      name: globalMobileAnomalyDetect
      template: object.json
      skip: false
      parameters:
        default: true
        slow:
          ###################
          ## slow - slowUserActions
          ## Fields:
          ## enabled - enabled
          ## mode - detectionMode - "auto","fixed"
          ## allDurThresh (both) - durationThresholdAllFixed/All 
          ## allPercent (auto) - slowdownPercentage
          ## slowDurThresh (both) - durationThresholdSlowest
          ## slowPercent (auto) - slowdownPercentage
          ## actPerMin (both) - minActionRate
          ## sens (fixed) - sensitivity - "low","medium","high"
          ##############
          type: value
          value:
            enabled: true
            mode: "auto"
            allDurThresh: 399
            allPercent: 10
            slowDurThresh: 1000
            slowPercent: 100
            actPerMin: 15
            sens: "low"
        error:
          ###################
          ## error - errorRate
          ## Fields:
          ## enabled - enabled
          ## mode - detectionMode - "auto","fixed"
          ## absInc (both) - thresholdAbsolute 
          ## relInc (auto) - thresholdRelative
          ## sens (fixed) - sensitivity - "low","medium","high"
          ##############
          type: value
          value:
            enabled: true
            mode: "auto"
            absInc: 50
            relInc: 100
            sens: "low"
        low:
          ###################
          ## low - unexpectedLowLoad
          ## Fields:
          ## enabled - enabled
          ## threshPercent - thresholdPercentage
          ##############
          type: value
          value:
            enabled: false
            threshPercent: 150
        high:
          ###################
          ## spike - unexpectedHighLoad
          ## Fields:
          ## enabled - enabled
          ## threshPercent - thresholdPercentage
          ##############
          type: value
          value:
            enabled: false
            threshPercent: 150