configs:
  - id: sloTemplate
    type: 
      settings:
        schema: builtin:monitoring.slo
        scope: environment
    config:
      name: 
        type: compound
        format: "{{.env}} - {{ .entity }} - {{.component}} - {{ .sli }}"
        references:
          - entity
          - sli
          - env
          - component
      template: object.json
      skip: false
      parameters:
        enabled: true
        ###################
        ## sli - determines type of slo
        ## values: perf, avail
        ###################
        sli: perf
        ###################
        ## entity - entityType 
        ## values: app, appmethod, service, keyservice
        ###################
        entity: keyservice
        ###################
        ## entity - environment 
        ## values: prod, qa, dev, etc.
        ###################
        env: prod
        ###################
        ## component - readable name of the entityType (lower case)
        ## values: any readable name
        ###################
        component: calculaterecommendations
        ###################
        ## filter - entitySelector (all must match)
        ## fields:
        ## - tag : "key:value"
        ## - name : "entityName"
        ## - id : "entityId"
        ###################
        filter:
          type: value
          value:
          - tag: project:easytravel
          - name: /CalculateRecommendations
        ###################
        ## threshold - use if sli = perf
        ## values: time in millisecond
        ###################
        threshold: 900
        ###################
        ## percentile - use if sli = perf, used to focus on percentile of data
        ## values: time in millisecond
        ###################
        percentile: 95
        target: 99
        warning: 99.98
        timeFrame: now-1d
        ###################
        ## action - use if app or appMethod
        ## values: load, xhr
        ###################
        action: load
        ###################
        ## burnRate - burnRateVisualizationEnabled
        ## fields:
        ## enabled : enabled
        ## fasBurnThreshold : fastBurnThreshold
        ###################
        burnRate:
          type: value
          value:
            enabled: true
            fastBurnThreshold: 10
  - id: sloTemplate2
    type: 
      settings:
        schema: builtin:monitoring.slo
        scope: environment
    config:
      name: 
        type: compound
        format: "{{.env}} - {{ .entity }} - {{.component}} - {{ .sli }}"
        references:
          - entity
          - sli
          - env
          - component
      template: object.json
      skip: false
      parameters:
        enabled: true
        sli: avail
        entity: keyservice
        env: prod
        component: calculaterecommendations
        filter:
          type: value
          value:
          - tag: project:easytravel
          - name: /CalculateRecommendations
        threshold: 900
        percentile: 95
        target: 99
        warning: 99.98
        timeFrame: now-1d
        action: load
        burnRate:
          type: value
          value:
            enabled: true
            fastBurnThreshold: 10
