configs:
  - id: globalMobileCrashAnomalyDetect
    type:
      settings:
        schema: builtin:anomaly-detection.rum-mobile-crash-rate-increase
        scope: environment
    config:
      name: globalMobileCrashAnomalyDetect
      template: object.json
      skip: false
      parameters:
        default: true
        crash:
          ###################
          ## crash - crashRateIncrease
          ## Fields:
          ## enabled - enabled
          ## mode - detectionMode - "auto","fixed"
          ## absInc (fixed) - absoluteCrashRate 
          ## conUser (both) - concurrentUsers
          ## percent (auto) - baselineViolationPercentage
          ## sens (auto) - sensitivity - "low","medium","high"
          ##############
          type: value
          value:
            enabled: true
            mode: "fixed"
            absInc: 20
            conUser: 100
            percent: 150
            sens: "low"