configs:
- id: serviceMutedRequests
  type:
    settings:
      schema: builtin:settings.mutedrequests
      #scopeFromSelector: type(service),entityName(easyTravel Customer Frontend)
      scope: SERVICE-AA9C6E2B8BEEC6D8
  config:
    name: exampleMutedRequest
    template: object.json
    skip: false
    parameters:
      muteReqNames:
        type: list
        values:
        - sds
        - sdsff