configs:
  - id: globalDatabaseAnomalyDetection
    type:
      settings:
        schema: builtin:anomaly-detection.databases
        scope: environment
    config:
      name: globalDatabaseAnomalyDetection
      template: object.json
      skip: false
      parameters:
        default: true
        resp:
          ###################
          ## resp - responseTime
          ## Fields:
          ## enabled - enabled
          ## mode - detectionMode - "AUTO","FIXED"
          ## degMilli (both) - degradationMilliseconds 
          ## degPercent (auto) - degradationPercent
          ## degSlowestMilli (both) - slowestDegradationMilliseconds
          ## degSlowestPercent (auto) - slowestDegradationPercent
          ## reqPerMin (both) - requestsPerMinute
          ## abState (both) - minutesAbnormalState
          ## sens (fixed) - sensitivity - "LOW","MEDIUM","HIGH"
          ##############
          type: value
          value:
            enabled: true
            mode: "auto"
            degMilli: 399
            degPercent: 10
            degSlowestMilli: 1000
            degSlowestPercent: 100
            reqPerMin: 15
            abState: 1
            sens: "low"
        fail:
          ###################
          ## fail - failureRate
          ## Fields:
          ## enabled - enabled
          ## mode - detectionMode - "AUTO","FIXED"
          ## absInc (auto) - absoluteIncrease 
          ## relInc (auto) - relativeIncrease
          ## reqPerMin (both) - requestsPerMinute
          ## abState (both) - minutesAbnormalState
          ## thresh (fixed) - threshold
          ## sens (fixed) - sensitivity - "LOW","MEDIUM","HIGH"
          ##############
          type: value
          value:
            enabled: true
            mode: "fixed"
            absInc: 50
            relInc: 100
            reqPerMin: 15
            abState: 1
            thresh: 50
            sens: "low"
        drop:
          ###################
          ## drop - loadDrops
          ## Fields:
          ## enabled - enabled
          ## percent - loadDropPercent
          ## abState - minutesAbnormalState
          ##############
          type: value
          value:
            enabled: false
            percent: 150
            abState: 2
        spike:
          ###################
          ## spike - loadSpikes
          ## Fields:
          ## enabled - enabled
          ## percent - loadSpikePercent
          ## abState - minutesAbnormalState
          ##############
          type: value
          value:
            enabled: false
            percent: 150
            abState: 2
        database:
          ###################
          ## database - databaseConnections
          ## Fields:
          ## enabled - enabled
          ## maxFailCon - maxFailedConnects
          ## timePer - timePeriod
          ##############
          type: value
          value:
            enabled: false
            maxFailCon: 6
            timePer: 6