configs:
  - id: globalK8sNamespaceAnomalyDetect
    type:
      settings:
        schema: builtin:anomaly-detection.kubernetes.namespace
        scope: environment
    config:
      name: globalK8sNamespaceAnomalyDetect
      template: object.json
      skip: false
      parameters:
        default: false
        cpuReq:
          ###################
          ## cpuReq - cpuRequestsQuotaSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5
            thresh: 90
        cpuLimit:
          ###################
          ## cpuLimit - cpuLimitsQuotaSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5
            thresh: 90
        memReq:
          ###################
          ## memReq - memoryRequestsQuotaSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5
            thresh: 90
        memLimit:
          ###################
          ## memLimit - memoryLimitsQuotaSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5
            thresh: 90
        pod:
          ###################
          ## pod - podsQuotaSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5
            thresh: 90
